name: praktek_app
description: Praktek Online.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+27

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.10.0
  cloud_firestore: ^2.5.4
  firebase_storage: ^10.2.4
  firebase_auth: ^3.1.4
  firebase_messaging: ^11.2.11
  flutter_flavorizr: ^2.1.3

  get: ^4.3.8
  flutter_form_builder: ^7.0.0
  google_sign_in: ^5.2.3
  firebase_analytics: ^8.3.4
  google_nav_bar: ^5.0.5
  form_builder_validators: ^7.1.0
  form_builder_extra_fields: ^7.0.0
  form_builder_phone_field: ^1.0.0-beta.0
  line_icons: ^2.0.1
  google_fonts: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  pin_code_fields: ^7.3.0
  url_launcher: ^6.1.2
  http: ^0.13.4
  whatsapp_unilink: ^2.0.0
  uuid: ^3.0.5
  dropdown_search: ^2.0.0
  dio: ^4.0.3
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.1
  badges: ^2.0.1
  flutter_vibrate: ^1.3.0
  cached_network_image: ^3.1.0+1
  location: ^4.3.0
  geocoding: ^2.0.1
  rive: ^0.7.33
  scan: ^1.5.0
  firebase_remote_config: ^2.0.8
  firebase_crashlytics: ^2.4.4
  firebase_performance: ^0.8.0+3
  qr_flutter: ^4.0.0
  permission_handler: ^8.3.0
  image_gallery_saver: ^1.7.1
  google_maps_flutter: ^2.1.1
  sliding_up_panel: ^2.0.0+1
  dotted_line: ^3.1.0
  shared_preferences: ^2.0.11
  image_cropper: ^1.4.1
  google_places_flutter: ^2.0.5
  flutter_local_notifications: ^9.1.5
  package_info_plus: ^1.3.0
  avatar_glow: ^2.0.2
  carousel_slider: ^4.0.0
  bootstrap_icons: ^1.5.0
  flutter_svg: ^1.0.3
  readmore: ^2.1.0
  timelines: ^0.1.0
  image_picker: ^0.8.4+9
  video_player: ^2.2.18
  mixpanel_flutter: ^1.4.5
  timer_builder: ^2.0.0
  http_parser: ^4.0.0
  overlay_support: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  json_theme: ^4.0.0+2
  jitsi_meet:
    git:
      url: https://github.com/dispersik/jitsi_meet_fork
      ref: master
  jitsi_meet_web: ^1.0.4
  cloud_functions: ^3.2.10
  dotenv: ^4.0.1
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.5.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/appainter_theme.json
    - assets/icon/icon.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    development:
      app:
        name: "Praktek (Dev)"
        icon: "assets/icon/icon-praktek-dev.png"


      android:
        applicationId: "io.praktek.dev"
        firebase:
          config: "firebase/development/google-services-praktek-dev.json"
        icon: "assets/icon/icon-praktek-dev.png"

      ios:
        bundleId: "io.praktek.dev"

    staging:
      app:
        name: "Praktek (Staging)"
        icon: "assets/icon/praktek-staging.png"


      android:
        applicationId: "io.praktek.staging"
        icon: "assets/icon/praktek-staging.png"
        firebase:
          config: "firebase/production/google-services.json"
      ios:
        bundleId: "io.praktek.staging"

    production:
      app:
        name: "Praktek"
        icon: "assets/icon/icon.png"

      android:
        applicationId: "io.praktek"
        firebase:
          config: "firebase/production/google-services.json"
        icon: "assets/icon/icon.png"

      ios:
        bundleId: "io.praktek"